### ISSUE TITLE
Incorrect is_revoked / revoke_token implementation on SessionDB?

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#268]
In `SessionDB.revoke_token`, you do:

```
    def revoke_token(self, token):
        typ, sid = self._get_token_type_and_key(token)
        _dict = self._db[sid]

        if typ == "A":
            _dict["code"] = ""
        elif typ == "T":
            _dict["access_token"] = ""
        else:
            pass
        self._db[sid] = _dict
        return True
```

But in `is_revoked`, you check for `revoked=True`, which is by default, set to `False`. 

`revoke_token` only sets the respective token to the empty string - why?

Is this wrong, or I'm missing something?

I saw expected results with:

```
class SessionDB(PyOIDCSessionDB):
    def revoke_token(self, token):
        """Revoke a token."""
        _, sid = self._get_token_type_and_key(token)
        session = self._db[sid]
        session['revoked'] = True
        self._db[sid] = session
```

**Comment by rohe** [comment]
It's a bug. In revoke_all_tokens() revoked is set to True. Same thing should have been done in revoke_token().

**Comment by rohe** [comment]
Still, an access token that has been removed from the SessionDB can not be used to access anything. It is in essence revoked even though not marked as such.

**Comment by lwm** [comment]
I've tried to make this change but ran into a lot of failing tests.  Question:  Regardless of whether `typ == "A" | "T"` should we still just set `revoked=True`? What is the relation between `revoked` and `typ`?

**Comment by rohe** [comment]
No real relationship between typ ad revoked. You should be able to revoke at any step in the process.

**Comment by lwm** [comment]
> No real relationship between typ and revoked.

Ah, maybe the current implementation was a red herring:

```python
    def revoke_token(self, token):
        """
        Revokes access token

        :param token: access token
        """
        typ, sid = self._get_token_type_and_key(token)
        _dict = self._db[sid]

        if typ == "A":
            _dict["code"] = ""
        elif typ == "T":
            _dict["access_token"] = ""
        else:
            pass
        self._db[sid] = _dict
        return True
```

Thanks, will take another look at this.

**Comment by rohe** [comment]
The parameter 'token' as used in the code can be an authorisation code (A) or an access token (T).
An authorisation code can only be used once so revoking it has to be done before it's used
the first time. When it's been used it is 'revoked' by default.
An access token on the other hand can be used multiple times therefor it should be possible to revoke at any time during its lifetime.

Now as to how to best revoke a token I seem to have been wavering.
1) Since a token is always checked against the session DB then setting the value to '' is a simple way of revoking it because what's in the session DB will *never* match a token. This does not open up the possibility that an attacker would send a zero length string as a token is verified as correct before being processed. 
2) A session variable 'revoked' could be used to signal the usability of the token.
Disregarding if it's an authorisation code or an access token.

Now I seem to have used both variants in there. We should chose one and go with that.
