### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#287]
Didn't take much time on this but first seen in https://travis-ci.org/OpenIDC/pyoidc/jobs/213191415.

**Comment by tpazderka** [comment]
I was digging a little bit into this.

The issue is in [sanitize](https://github.com/OpenIDC/pyoidc/blob/master/src/oic/utils/sanitize.py#L10) as it will keep `B` or `U` before the `<REDACTED>` if the sensitive part is starting with it.

So it is not an error in test but rather a bug in `sanitize` function...

`sanitize('code=bttt')` => `code=b<REDACTED>`
