### ISSUE TITLE
oic.util.keyio.proper_path produces bogus results on Windows

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#352]
The `proper_path` method in the keyio module produces broken pathes on windows, as it does not handle drive letters in any way.

This leads to a test failure on windows, when running `TestProvider.test_provider_key_setup`, as the `os.makedirs` gets some path looking like `./c:' and doesn't like that.

I'm not sure what the code should really do, as the desired usage of `proper_path` isn't really clear to me, it looks a bit like it is mostly wishful thinking. It seems to try to produce some kind of relativ path (which might be impossible for windows sometimes, e.g. if files reside on different drive letters).

The usage seems a little odd too, especially in `key_export()`. It doesn't make much sense to concatenate the exported URL path with some local path and expect the result to be sane. Those two pathes might have no relation at all besides some mapping in some web server or reverse proxy configuration.

It would help to document the expectations/path vs URL layout ideas behind the keyio code a bit.

**Comment by lwm** [comment]
> I'm not sure what the code should really do, as the desired usage of proper_path isn't really clear to me, it looks a bit like it is mostly wishful thinking. It seems to try to produce some kind of relativ path (which might be impossible for windows sometimes, e.g. if files reside on different drive letters).

> The usage seems a little odd too, especially in key_export(). It doesn't make much sense to concatenate the exported URL path with some local path and expect the result to be sane. Those two pathes might have no relation at all besides some mapping in some web server or reverse proxy configuration.

@rohe, this is certainly a job for you!

**Comment by rohe** [comment]
I'm been using Unix or Unix like OS's since late 80's so I have no recent experience of Windows or similar systems. There have also not been any pressure from my immediate surrounding to deal with anything but Unix like system. Due to this I'm sure there are a number of things that doesn't work on Windows. If you want to fix this please go ahead.

Regarding the other issue; yes I have assumed that there is a simple map between a URL and a local path. Again this is the environment I've worked and is working within.
I do belive there has to be some function you can use to go from one to the other, albeit it might be more complex then I believed it would have to be.

**Comment by schlenk** [comment]
ok. Yes, just one OS tradition makes things so much simpler. 

I'll have a look and see if i can figure out the assumptions. Should not be too many (i have it running on Windows, so it works in principle, just some tests blow up currently, and to fix those i need the assumptions.)

**Comment by tpazderka** [comment]
@schlenk Any luck on this? I personally think that we should rethink the `keyio` as a whole since it assume so many things.
