### ISSUE TITLE
Issuers JWKS contains several keys while JWT header contains no 'kid'

### ISSUE THREAD

**Issue by rohe** [OpenIDC/pyoidc#378]
According to the standard, if an issuers JWKS contains several keys that can be used for the same purpose (signing) then the header of a signed JWT **MUST** contain a 'kid' pointing to which key was used.

Presently the code is _lax_ on this. It allows the 'kid' to be missing and will just loop through all the possible keys until it finds one that works or none.

The OIDF RP library test suite expects the library to be _strict_ and reject a signed JWT if no 'kid' is present given the above mentioned circumstances.

Should I make the code be strict ??
Should it be configurable ?

**Comment by lwm** [comment]
> Should it be configurable ?

Probably! Unless not being strict is just wrong. Which doesn't appear to be the case?

**Comment by rohe** [comment]
We're in total agreement so far.

Next thing: Should it be per issuer or .. ?

**Comment by schlenk** [comment]
The kid, issuer tuple should obviously match the issuer and no search across JWKS of different issuers should happen, but the question seems about the exception to the strict check.

I think it would be best to have some kind of mapping. For each issuer you trust, you can either accept all keys, or just a specific subset.

A bit like this:

    if not jws.get('kid') and issuer in no_kid_issuers:
           allowed_kids = no_kid_issuers[issuer]
           if not allowed_kids:
                # loop over all kids in the jwks, like today
           else:
                # loop over all kids in the allowed_kids list

This would allow it to block certain keys you do not want to trust for policy reasons, or because you know those are revoked but the jwks is still cached somewhere in between.

**Comment by rohe** [comment]
Not being strict is going back to the old John Postel statement:
'an implementation must be conservative in its sending behavior, and liberal in its receiving behavior.'

So, I think it's a reasonable stance to take.
