### ISSUE TITLE
Let's get rid of custom dependency management and use pipenv

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#395]
PR on the way!

http://pipenv.org

**Comment by schlenk** [comment]
After some struggling, finally forced pipenv to build a venv for pyoidc on Windows.

Should probably dump it in the documentation, but for now, a small rundown here:

1. Install pipenv 
2. Set PATH environment to a path that includes `pipenv.exe`

    `SET PATH = %PATH%; <path to pipenv.exe dir>`

3. Decide where you want your venvs to be created and set WORKON_HOME to the appropriate path.

    The default is some dotfile path in the user profile, that should have been in %LOCALAPPDATA%
    instead of below %HOMEPATH%. .

    `SET WORKON_HOME c:\myvenvs`

4. (Optional) Switch off a few annoying Pipenv things:

    Disable unreadable coloured output (unless you change your console background colour)

    `SET PIPENV_COLORBLIND=1`

    'pipenv shell' seems to be totally broken. Either it spawns a powershell that is unusable (keyboard
    input goes anywhere but not to the shell) or if you add SHELL and PIPENV_SHELL_COMPAT
    environment variables you get a shell, without command history and not inside the venv as the docs
    promised.

5. (Optional) Provide a working pyldap wheel, instead of trying to build it yourself, which will
    probably fail unless you install a gazillion dependencies that won't build easily with VC2008 first.

    Get the wheels for your python version from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyldap
    
    Place them in a local directory like: `c:\myvenvs\dependencies\pyldap`

    Now tell PIP to look there, either via config or another environment variable:

    `SET SET PIP_FIND_LINKS=file:///c:/myvenvs/dependencies/`

6. Set an environment variable to your `python.exe` path, to save typing
    
    `SET PPATH=c:\Python27\python.exe`

6. Run `pipenv `, but you need to add the path of your python

    `pipenv --python %PPATH% install --dev`

7. Wait (a lot) and hope it works...




    `

**Comment by lwm** [comment]
Holy moly, sorry to hear it was such a struggle!

**Comment by schlenk** [comment]
Well, not far from the usual Windows masochism experience with Python. Especially with bleeding edge things. There are lots of dark corners that fail in surprising (sometimes documented) ways on windows when using Python. 

Played a bit more with pipenv (and filed two bugs...), and see why you and others might like it.

I think pipenv is great for CI setups or other automated deployments.
The declarative Pipfiles and the lock parts with hashes make for a nicely reproducible environment.

For development use it still has quite a few warts, i think, most probably a matter of being rather new.

- It is pretty slow (on Windows at least), as starting lots and lots of wrapper processes is slow (a typical pipenv shell is an 8 levels deep process tree (!))
- pipenv seems to assume i only want exactly one virtualenv per source tree, for mixed Py2/Py3 projects i typically have at least 2 (see the issue here https://github.com/kennethreitz/pipenv/issues/368 ), not sure how the switching via `--python` works, as i typically have two shells open that run py2/py3 tests 
- `pipenv shell` seems to be broken on my machine, but explicit activate in the venv works (see https://github.com/kennethreitz/pipenv/issues/435 for the story...)
- As usually with these 'i do all for you' approaches, when things fail, you are pretty lost. The default logging is pretty but useless for troubleshooting (e.g. the progress bar tells you just that a package is getting installed but not which ones). And you need to know lots of different tools to find the right switches to make it work. (pip, pew, pipenv, thats 3 too many).
- It all seems pretty bleeding edge. Sometimes it feels like 'its new, its shiny, i want it' instead of technical reasons for some choices.

So, guess we can keep it. Its not seriously more broken than all the other package managers.
