### ISSUE TITLE
Extra claims for id_token

### ISSUE THREAD

**Issue by mshevyakov** [OpenIDC/pyoidc#500]
Hi guys, in my application I need to know the method used to authenticate user ("amr" claim in id_token). If I got right it could be done by adding extra_claims parameter when calling

https://github.com/OpenIDC/pyoidc/blob/3f21791df99aad8764b3ce796ba5689241ca86c4/src/oic/oic/provider.py#L338-L340

which is called by
https://github.com/OpenIDC/pyoidc/blob/3f21791df99aad8764b3ce796ba5689241ca86c4/src/oic/oic/provider.py#L871-L874

but there's no extra_claim parameter here.
Don't you think extra_claims parameter should be added in this call as well as in
https://github.com/OpenIDC/pyoidc/blob/3f21791df99aad8764b3ce796ba5689241ca86c4/src/oic/oic/provider.py#L845-L846

?

**Comment by tpazderka** [comment]
I think you should be able to get the `amr` claim by including it in the [request](http://openid.net/specs/openid-connect-core-1_0.html#IDToken).

**Comment by ermakoves** [comment]
> I think you should be able to get the amr claim by including it in the request.
I think this is will not work:
1) https://github.com/OpenIDC/pyoidc/blob/f1d7e29a3d60fa7bfc5b65a30be211a786839a8e/src/oic/oic/__init__.py#L1763-L1773
OIDC ignored amr option

2) By default request will filtered amr claim:
https://github.com/OpenIDC/pyoidc/blob/f1d7e29a3d60fa7bfc5b65a30be211a786839a8e/src/oic/oic/provider.py#L665-L675

3) And main problem - how to store amr value\values at provider ?

**Comment by tpazderka** [comment]
Ah, yes, you are correct, I confused it with `acr`.

**Comment by ermakoves** [comment]
So, how to set correctly amr ?

**Comment by tpazderka** [comment]
It looks to me that this is not implemented yet.

**Comment by schlenk** [comment]
Looked into it too, it is indeed not implemented yet. 

There is no easy way for the authn plugins to setup their amr value. It should probably be included in AuthnEvent, but that just contains the acr currently. Would need some protocol how to pass it through the redirect dance. MultiAuthn would need some extra work too.

Setting the amr can be done by adding extra_args to the `id_token_as_signed_jwt()` call in the provider as you noticed correctly, but needs a subclassed provider right now, as there is no way to add the parameter otherwise. That actually works and an amr value is included in the IdToken.

But currently amr is a little useless anyway, unless you implemented your own MultiAuthn method that does not chain authn with logical 'and', as acr is a 1:1 mapping to the amr values you would get, due to the way the acr/proper authn plugins are selected, you always get the one with the highest level for your authnbroker and asked for acr.

So you could do the following:
1) Have a map that maps acr <-> amr
2) Extend the provider class and setup the extra_args in the overriden id_token_as_signed_jwt() before calling the base class version.

A bit like this, you would need to add a `map_acr2amr()` that does the right thing for you.

```python
class MyProvider(Provider):
    def id_token_as_signed_jwt(self, session, loa="2", alg="", code=None, access_token=None, user_info=None, auth_time=0, exp=None, extra_claims=None, **kwargs):

        # We need to put the 'amr' values into extra_claims
        if extra_claims is None:
             extra_claims = {}
        _authn_event = AuthnEvent.from_json(session["authn_event"])
        acr = _auth_event.authn_info
        amr = map_acr2amr(acr)
        extra_claims.update({'amr': [amr]})
        return super(MyProvider, self).id_token_as_signed_jwt(
            session, loa, alg, code, access_token, user_info, auth_time,
            exp, extra_claims, **kwargs)
```
