### ISSUE TITLE
allow http support for localhost in development environment

### ISSUE THREAD

**Issue by nazrulworld** [OpenIDC/pyoidc#556]
Hi,
I understand the strict policy about https scheme for any OP url, but for development environment I think if localhost is allowed to use http would be better. Or we could use any special environmental variable which could allow to use http url scheme

**Comment by schlenk** [comment]
Why do you think you need http for development? What is the usecase?
A TLS setup for development is easy, with self signed certificates or even with Let's encrypt certificates.

In any case:
localhost should already work with http for 'native' apps. So you could simply register your app as 'native' instead of 'web' as application_type.

For non native apps, it is explicitly disallowed by the standard:
https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata

OAuth2 is insecure if not used with a TLS layer.

**Comment by nazrulworld** [comment]
@schlenk firstly thanks a lot for reply

My Use Case: I am trying to implement pyoidc within [Plone](https://plone.org). Here I need to run unittest, thus plone is making test server available in localhost with random port. so port number is not static.
I completely agree with your opinion   

> A TLS setup for development is easy
I am not expert on that, can you please help me to setup TLS for localhost with any port number?

**Comment by schlenk** [comment]
I don't really know Plone. So maybe ask in a plone specific forum about that.

Usually development servers offer a way to work with TLS too, if you have a certificate for the hostname available. Some can even generate it on the fly (e.g flask does that).

You either use something like letsencrypt (https://letsencrypt.org/docs/) e.g. if your test setup runs in a cloud deployment. Or you can use openssl commandline to create your own 'self-signed certificates' for your hostname. On Windows even powershell has a builtin command for that `New-SelfSignedCertificate'. Google finds hundreds of descriptions to create self-signed certificates.

The port doesn't really matter, a certificate just holds the hostname.

Closing this, as it is a bit off-topic for pyoidc.
