### ISSUE TITLE
email_verified parameter

### ISSUE THREAD

**Issue by psnehal** [OpenIDC/pyoidc#757]
I am running    `user_info = client.do_user_info_request(
            access_token=access_token2)`

and getting below error:

`oic.oauth2.message.ParameterError
oic.oauth2.message.ParameterError: "true", wrong type of value for "email_verified"`

As per OIDC specification, "true" is a valid value for email_verified. SO I was wondering what is causing the error.

**Comment by tpazderka** [comment]
As per the spec, `email_verified` should be a boolean. Your response contains a string representation instead.

**Comment by psnehal** [comment]
is there any way if we can ignore the email_verfied option? as this is coming from university, I dodnt have control over the value coming from open id request.

**Comment by schlenk** [comment]
You could try just asking for the claims you actually need instead of the scope email, but as the OP might include the malformed value anyway this may or may not work (see https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter).

The other option would be to pass in a kwarg "user_info_schema" into the `do_userinfo_request` method to override the Schema used for validating the response and use your own Schema class derived from OpenIDSchema (see message.py), there you could redefine the email_verified claims data type.
