### ISSUE TITLE
Failed to decode error response for HTTP 200

### ISSUE THREAD

**Issue by rizart** [OpenIDC/pyoidc#821]
Hello,

In this case:
https://github.com/OpenIDC/pyoidc/blob/64c5e3b6c099496787093a778fbc8b0d7e044e1d/src/oic/oauth2/__init__.py#L772
if the `status_code` is `200` , an Exception is logged. 
Not sure what's the logic of having the `200` success code in the same clause as `400` & `401`.

P.S. 
I was using `oic==1.3.0`, just tried `1.4.0` with same results.

**Comment by schlenk** [comment]
Do you have some specific use/flow where you run into that if with a 200 status code?

I fixed some glitches in that code with https://github.com/OpenIDC/pyoidc/pull/817 so if you could retry with the head to verify that would be helpful. The code before that would raise an Exception trying to decode the error response due to a wrong attribute name used.

Basically the code assumes that the expected `reponse` message class is passed in and only hits the 200 when that happens.

**Comment by rizart** [comment]
I can confirm that #817 solves this issue, many thanks for the prompt answer @schlenk!
